env: "local"
rabbit_addr: "amqp://guest:guest@localhost:5672/"
http_server:
  address: "0.0.0.0:8083"
  timeout: 4s
  idle_timeout: 30s
email:
  from: "balasanianraf@yandex.ru"
  password: "tgjulhqwvgtjwups"
  smtp_host: "smtp.yandex.ru"
  smtp_port: 465