env: "local"
jwt_secret: "R7q1FxEvPjZnLm1vZkD2x3lht9q4B8xJ3HVYqQ=="
http_server:
  address: "0.0.0.0:8081"
  timeout: 4s
  idle_timeout: 30s
kafka:
  broker: "localhost:29092"
  topic: "test-topic"
  groupID: 123
