env: "local"
storage_path: "username:password@protocol(address)/dbname?param=value"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s
kafka:
  broker: "localhost:29092"
  topic: "test-topic"
  groupID: 134
