env: "local"
mongo_uri: "mongodb://mongo:root@localhost:27017/"
redis_addr: "localhost:6379"
redis_password: "mysecretpassword"
rabbit_addr: "amqp://guest:guest@localhost:5672/"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s
kafka:
  broker: "localhost:29092"
  topic: "test-topic"
  groupID: 123
